import os

# App Name
APP_NAME = 'NSE_SCRAPPER'

# Config vars
APP_CONFIG_ENV = APP_NAME + "_CONFIG"
DEV_CONFIG_VAR = "development"
PROD_CONFIG_VAR = "production"
SECRET_KEY = APP_NAME + '_SECRET_KEY'
SECURITY_PASSWORD_SALT = APP_NAME + '_SECURITY_PASSWORD_SALT'
DATABASE_URI = APP_NAME + "_DATABASE_URI"
